### ISSUE TITLE
[BUG] Won't start because IndexError: list index out of range

### ISSUE THREAD

**Issue by JindrazPrahy** [kraanzu/dooit#118]
I run the latest Arch Linux and dooit won't start for me. I get the following error:

```
Traceback (most recent call last):
  File "/home/jin/.local/bin/dooit", line 5, in <module>
    from dooit.__init__ import main
  File "/home/jin/.local/lib/python3.11/site-packages/dooit/__init__.py", line 3, in <module>
    from .ui.tui import Dooit
  File "/home/jin/.local/lib/python3.11/site-packages/dooit/ui/tui.py", line 6, in <module>
    from dooit.ui.widgets import WorkspaceTree, TodoTree, StatusBar, HelpScreen
  File "/home/jin/.local/lib/python3.11/site-packages/dooit/ui/widgets/__init__.py", line 1, in <module>
    from .status_bar import StatusBar
  File "/home/jin/.local/lib/python3.11/site-packages/dooit/ui/widgets/status_bar.py", line 8, in <module>
    from dooit.api import manager
  File "/home/jin/.local/lib/python3.11/site-packages/dooit/api/__init__.py", line 2, in <module>
    from .manager import Manager, manager
  File "/home/jin/.local/lib/python3.11/site-packages/dooit/api/manager.py", line 83, in <module>
    manager.setup()
  File "/home/jin/.local/lib/python3.11/site-packages/dooit/api/manager.py", line 61, in setup
    self.from_data(data)
  File "/home/jin/.local/lib/python3.11/site-packages/dooit/api/manager.py", line 67, in from_data
    child.from_data(j)
  File "/home/jin/.local/lib/python3.11/site-packages/dooit/api/workspace.py", line 54, in from_data
    todo.from_data(data)
  File "/home/jin/.local/lib/python3.11/site-packages/dooit/api/todo.py", line 148, in from_data
    child_todo.from_data(i)
  File "/home/jin/.local/lib/python3.11/site-packages/dooit/api/todo.py", line 144, in from_data
    self.fill_from_data(data[0])
  File "/home/jin/.local/lib/python3.11/site-packages/dooit/api/todo.py", line 127, in fill_from_data
    self._urgency.from_txt(data)
  File "/home/jin/.local/lib/python3.11/site-packages/dooit/api/model_items.py", line 293, in from_txt
    self.set(txt.split()[1][1])
             ~~~~~~~~~~~^^^
IndexError: list index out of range
```

I get this error upon running dooit  installed through pip and also if it's installed through the AUR. I encountered the error on both of my PCs.
The last version that works for me is dooit 0.2.1.

Maybe it's a conflicting dependency? Although idk which one.

**Comment by kraanzu** [comment]
Hi @JindrazPrahy, is this a fresh install or you've updated the packages?

**Comment by JindrazPrahy** [comment]
Hi, I've done both a fresh install and a package update from 0.2.1 to 1.0.1 and encountered the same issue.
But (re)installing the downgraded version worked for me.

**Comment by kraanzu** [comment]
Hmm....If possible can you share the `todo.yaml` file?
You can get the path by running this command:

```bash
python -c "import appdirs; print(appdirs.user_data_dir('dooit'))"
```

**Comment by JindrazPrahy** [comment]
Sorry, I don't want to share the todo.yaml file as it contains my personal info.

However, you were right in suspecting that the todo.yaml file caused the error. I manually wrote down my TODOs to back them up and then deleted the todo.yaml -> this fixed the issue.

In my mental model, the todo.yaml file wasn't a part of the application itself (just like when you edit a file with vim, the file you are editing isn't a part of vim), that's why I didn't suspect that it might be causing problems.

I consider my issue resolved with this, so I'm closing the bug report.

**Comment by kraanzu** [comment]
> Sorry, I don't want to share the todo.yaml file as it contains my personal info.

Well ofcourse, I was just asking for a dummy data that was getting saved in the yaml file haha 

I'm glad it all worked out!
