### ISSUE TITLE
[BUG] Blank screen on launch (Windows)

### ISSUE THREAD

**Issue by cpkio** [kraanzu/dooit#17]
**Describe the bug** 🐛
Blank screen on launch in Windows.

**To Reproduce** 🐣
1. Install
2. Try to run `dooit`

**Expected behavior**  🤔 
I'd like to see some UI.

**Desktop (please complete the following information):**  🤖
 - OS: Windows 10 x64

**Comment by kraanzu** [comment]
I haven't tried this on windows but a black screen doesn't sound right.
There is no output ? Like no errors? Just black screen?
Also, are you on the new windows terminal?

**Comment by MassimoCastell** [comment]
Tested it on Windows. There is probably a codepage issue. 

`Traceback (most recent call last):
  File "C:\Python\Python310\lib\site-packages\dooit\utils\config.py", line 61, in check_files
    self.keybinds = self.load_keybindings()
  File "C:\Python\Python310\lib\site-packages\dooit\utils\config.py", line 76, in load_keybindings
    keybinds = self.load_config("keybindings")
  File "C:\Python\Python310\lib\site-packages\dooit\utils\config.py", line 70, in load_config
    return yaml.safe_load(stream)[part]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python310\Scripts\dooit.exe\__main__.py", line 4, in <module>
  File "C:\Python\Python310\lib\site-packages\dooit\__init__.py", line 1, in <module>
    from .ui.tui import Doit
  File "C:\Python\Python310\lib\site-packages\dooit\ui\tui.py", line 1, in <module>
    from dooit.utils.parser import Parser
  File "C:\Python\Python310\lib\site-packages\dooit\utils\__init__.py", line 1, in <module>
    from .parser import Parser
  File "C:\Python\Python310\lib\site-packages\dooit\utils\parser.py", line 4, in <module>
    from dooit.ui.widgets.entry import Entry
  File "C:\Python\Python310\lib\site-packages\dooit\ui\widgets\__init__.py", line 5, in <module>
    from .box import Box
  File "C:\Python\Python310\lib\site-packages\dooit\ui\widgets\box.py", line 9, in <module>
    from dooit.utils.config import conf
  File "C:\Python\Python310\lib\site-packages\dooit\utils\config.py", line 85, in <module>
    conf = Config()
  File "C:\Python\Python310\lib\site-packages\dooit\utils\config.py", line 45, in __init__
    self.check_files()
  File "C:\Python\Python310\lib\site-packages\dooit\utils\config.py", line 65, in check_files
    self.make_new_config()
  File "C:\Python\Python310\lib\site-packages\dooit\utils\config.py", line 50, in make_new_config
    stream.write(f.read())
  File "C:\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 262: character maps to <undefined>
`

**Comment by kraanzu** [comment]
@MassimoCastell  This is due the default icon's font.
Try using a [nerd font](https://www.nerdfonts.com/)

**Comment by cpkio** [comment]
@kraanzu No, I'm using ConEmu for a few years least. This is not terminals fault. Term encoding is UTF8, which works fine for tens of console apps I use.

**Comment by kraanzu** [comment]
Hey @cpkio, turns out that textual is causing the issue 
Here: https://github.com/Textualize/textual/discussions/335?sort=old

Try and see if the solutions provided works? Good Luck!

**Comment by cpkio** [comment]
@kraanzu I dont see any solutions there… `dooit` works in NuShell somehow

**Comment by kraanzu** [comment]
Well ...Anything is better than nothing :)
So should we close this now?
