### ISSUE TITLE
[BUG] Application fails with a `KeyError: 'show_headers'` error

### ISSUE THREAD

**Issue by superatomic** [kraanzu/dooit#39]
**Describe the bug** 🐛
When launching `dooit`, the application exits with the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/dooit", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/dooit/__init__.py", line 5, in main
    Doit.run()
  File "/usr/local/lib/python3.10/site-packages/textual/app.py", line 206, in run
    asyncio.run(run_app())
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/textual/app.py", line 204, in run_app
    await app.process_messages()
  File "/usr/local/lib/python3.10/site-packages/textual/app.py", line 291, in process_messages
    await self.dispatch_message(load_event)
  File "/usr/local/lib/python3.10/site-packages/textual/message_pump.py", line 232, in dispatch_message
    await self.on_event(message)
  File "/usr/local/lib/python3.10/site-packages/textual/app.py", line 434, in on_event
    await super().on_event(event)
  File "/usr/local/lib/python3.10/site-packages/textual/message_pump.py", line 254, in on_event
    await invoke(method, event)
  File "/usr/local/lib/python3.10/site-packages/textual/_callback.py", line 29, in invoke
    result = await result
  File "/usr/local/lib/python3.10/site-packages/dooit/ui/tui.py", line 67, in on_load
    self.show_header = conf.load_config()["show_headers"]
KeyError: 'show_headers'
```

**To Reproduce** 🐣
1. Run `python3 -m pip install git+https://github.com/kraanzu/dooit.git` as described in the [README.md](https://github.com/kraanzu/dooit/blob/main/README.md)
2. Run `dooit`

**Expected behavior**  🤔 
The app runs without an error.

**Desktop (please complete the following information):**  🤖
 - OS: macOS 12.4
 - Version: `HEAD`

**Additional context** 📝
It seems like commit https://github.com/kraanzu/dooit/commit/2aa9e7663db1bb90bc4348a09682e106dde06a3f, which closed #29, has caused this problem.

**Comment by kraanzu** [comment]
My bad... I need to re-write the config.
I'll push an update rn :(
