### ISSUE TITLE
ERROR: Package 'dooit-0.2.0' requires a different Python: 3.8.10 not in '>=3.10,<4.0'

### ISSUE THREAD

**Issue by termunix** [kraanzu/dooit#55]
when i try to install it using pip3 install .
it says:
"ERROR: Package 'dooit-0.2.0' requires a different Python: 3.8.10 not in '>=3.10,<4.0'"
same thing when i use the one liner
i thought it was because of my python version so i checked
when i run python3.10 --version
it says i have 3.10.5
how do i fix this?
 - OS: [Linux mint]

**Comment by kraanzu** [comment]
Try this:
```
python3.10 -m pip install git+https://github.com/kraanzu/dooit.git
```

**Comment by termunix** [comment]
when i did it outputs this

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/pip/__main__.py", line 16, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 19, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils.util'

**Comment by kraanzu** [comment]
I think you have both versions of python which is causing the issue...try removing the older version first :)

**Comment by brizzz** [comment]
i have this error:

Traceback (most recent call last):
  File "/Users/brizzz/.pyenv/versions/3.10.4/lib/python3.10/site-packages/psutil/_psosx.py", line 343, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/brizzz/.pyenv/versions/3.10.4/lib/python3.10/site-packages/psutil/_psosx.py", line 401, in cmdline
    return cext.proc_cmdline(self.pid)
ProcessLookupError: [Errno 3] assume no such process (originated from sysctl(KERN_PROCARGS2) -> EINVAL)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brizzz/.pyenv/versions/3.10.4/bin/dooit", line 8, in <module>
    sys.exit(main())
  File "/Users/brizzz/.pyenv/versions/3.10.4/lib/python3.10/site-packages/dooit/__init__.py", line 24, in main
    if is_running():
  File "/Users/brizzz/.pyenv/versions/3.10.4/lib/python3.10/site-packages/dooit/__init__.py", line 10, in is_running
    counter += process.name() in ["dooit", "dooit.exe"]
  File "/Users/brizzz/.pyenv/versions/3.10.4/lib/python3.10/site-packages/psutil/__init__.py", line 628, in name
    cmdline = self.cmdline()
  File "/Users/brizzz/.pyenv/versions/3.10.4/lib/python3.10/site-packages/psutil/__init__.py", line 681, in cmdline
    return self._proc.cmdline()
  File "/Users/brizzz/.pyenv/versions/3.10.4/lib/python3.10/site-packages/psutil/_psosx.py", line 348, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=2712)

macOS

**Comment by kraanzu** [comment]
Hey @brizzz , I've pushed an update... Maybe try again after updating?

**Comment by brizzz** [comment]
@kraanzu thanks! After reinstall it works!

**Comment by ngmisl** [comment]
@kraanzu getting the same now, tried with pip3.9, pip3.10 and python3.8

ERROR: Package 'dooit' requires a different Python: 3.9.7 not in '<4.0,>=3.10'

**Comment by kraanzu** [comment]
@ngmisl  It's because of your python version!
In the updated version (releasing in a couple of hours) this won't be the case anymore so closing this issue
