### ISSUE TITLE
[BUG] For python3.8 and python3.9, dooit cannot startup normally.

### ISSUE THREAD

**Issue by Weissle** [kraanzu/dooit#99]
**Describe the bug** 🐛
Met error when using python3.8 or 3.9 to run dooit.

**To Reproduce** 🐣
1. Use python3.8 or python3.9.
2. Under the root of dooit, `python main.py`

**Expected behavior**  🤔 
dooit starts up normally.

**Screenshots** 🧐
For python3.8
```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from dooit.__init__ import main
  File "/home/weissle/learn/dooit/dooit/__init__.py", line 3, in <module>
    from .ui.tui import Dooit
  File "/home/weissle/learn/dooit/dooit/ui/tui.py", line 4, in <module>
    from dooit.utils.watcher import Watcher
  File "/home/weissle/learn/dooit/dooit/utils/__init__.py", line 4, in <module>
    from .keybinder import KeyBinder
  File "/home/weissle/learn/dooit/dooit/utils/keybinder.py", line 57, in <module>
    configured_keys = DEFAULTS | configured_keys
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
```
For python3.9
```
Traceback (most recent call last):
  File "/home/weissle/learn/dooit/main.py", line 1, in <module>
    from dooit.__init__ import main
  File "/home/weissle/learn/dooit/dooit/__init__.py", line 3, in <module>
    from .ui.tui import Dooit
  File "/home/weissle/learn/dooit/dooit/ui/tui.py", line 6, in <module>
    from dooit.ui.widgets import WorkspaceTree, TodoTree, StatusBar, HelpScreen
  File "/home/weissle/learn/dooit/dooit/ui/widgets/__init__.py", line 2, in <module>
    from .sort_options import SortOptions
  File "/home/weissle/learn/dooit/dooit/ui/widgets/sort_options.py", line 14, in <module>
    class SortOptions(Widget):
  File "/home/weissle/learn/dooit/dooit/ui/widgets/sort_options.py", line 23, in SortOptions
    name: str | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Desktop (please complete the following information):**  🤖
 - OS: WSL
 - Version Ubuntu 20.03

**Additional context** 📝

**Comment by kraanzu** [comment]
I see. Thanks for the PR! I thought that the `match` statements were the only thing keeping it from running on lower versions of python :confused: 

 Would you like to work on this @Weissle ?

**Comment by Weissle** [comment]
Will take a look when I have time.
